# Generated by Django 5.1.3 on 2025-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_options_player_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='aerial_duel_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='appearance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='assist',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='assist_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ball_recovered_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='clearance_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbled_past_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='error_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goal_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='key_pass_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='long_ball_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shot_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sot_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='successful_crossing_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='successful_dribble_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='successful_pass_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_duel_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
