# Generated by Django 5.1.3 on 2025-10-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_rename_player_name_player_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
