# Generated by Django 5.1.3 on 2025-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_rename_dataset_player_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='naturalisasi',
            field=models.BooleanField(default=False),
        ),
    ]
