# Generated by Django 5.1.3 on 2025-11-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_naturalisasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='League',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='season',
            new_name='league',
        ),
    ]
